/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DB.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoeAlpha
 */
public class Crud extends javax.swing.JFrame {

    /**
     * Creates new form Crud
     */
    public Crud() {
        initComponents();
        users_table();
        
        // creating button group for gender radio buttons
        ButtonGroup bgGroup = new ButtonGroup();
        bgGroup.add(btnMale);
        bgGroup.add(btnFemale);
        
        btnViewStud.setVisible(false);
        btnUpdtRecord.setVisible(false);
        btnDelStud.setVisible(false);
        
        // center the form
        this.setLocationRelativeTo(this);
    }
    
    // create a variable for connection to the database     
    PreparedStatement sqlQueryCheck;     
    PreparedStatement sqlQueryInsert; 
    PreparedStatement sqlQueryUpdate;
    ResultSet res;
    Connection conn;
    
    DefaultTableModel defaulttbl_1_query;
    DefaultTableModel defaulttbl_2_view;
    DefaultTableModel defaulttbl_3_delete;
    DefaultTableModel defaulttbl_4_update;
    DefaultTableModel defaulttbl_5_update;
    DefaultTableModel defaulttbl_6_update;
    
    // function view all lecturers
    private void users_table() {
        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_users");
            res = sqlQueryCheck.executeQuery();
            
            while(res.next()) {
                String userId     = res.getString("id");
                String userFirst  = res.getString("firstname");
                String userLast   = res.getString("lastname");
                String userPhone  = "0"+res.getString("phone");
                String userGender = res.getString("gender");
                
                Object[] obj = {userId, userFirst, userLast, userPhone, userGender};
                
                defaulttbl_1_query = (DefaultTableModel)tbl_users.getModel();
                defaulttbl_1_query.addRow(obj);
            }
        } catch (Exception ex) {
            Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // function of clearing the form
    private void clear_form() {
        txtFname.setText("");
        errorFname.setText(null);
        if(txtFname.getText().trim().equals("")){
            txtFname.setText("first name");
            txtFname.setForeground(Color.gray);
            FnameLine.setBackground(Color.black);
        }
        
        txtLname.setText("");
        errorLname.setText(null);
        if(txtLname.getText().trim().equals("")){
            txtLname.setText("last name");
            txtLname.setForeground(Color.gray);
            LnameLine.setBackground(Color.black);
        }
        
        txtPhone.setText("");
        errorPhone.setText(null);
        if(txtPhone.getText().trim().equals("")){
            txtPhone.setText("07xxxxxxxx");
            txtPhone.setForeground(Color.gray);
            PhoneLine.setBackground(Color.black);
        }
        
        txtEmail.setText("");
        errorEmail.setText(null);
        if(txtEmail.getText().trim().equals("")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            EmailLine.setBackground(Color.black);
        }
        
        txtPassword.setText("");
        errorPassword.setText(null);
        if(txtPassword.getText().trim().equals("")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            PasswordLine.setBackground(Color.black);
        }
        
        txtConfirm.setText("");
        if(txtConfirm.getText().trim().equals("")){
            txtConfirm.setText("yourpassword");
            txtConfirm.setForeground(Color.gray);
            ConfirmLine.setBackground(Color.black);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        btnShowAllStud = new javax.swing.JButton();
        btnDelStud = new javax.swing.JButton();
        btnGoToAddStud = new javax.swing.JButton();
        btnUpdtRecord = new javax.swing.JButton();
        btnViewStud = new javax.swing.JButton();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_users = new rojeru_san.complementos.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userFname = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        userLname = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        userGender = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        userIdNo = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        userStatus = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        userPhone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        FnameLine = new javax.swing.JLabel();
        errorFname = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        LnameLine = new javax.swing.JLabel();
        errorLname = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        PhoneLine = new javax.swing.JLabel();
        errorPhone = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnFemale = new javax.swing.JRadioButton();
        btnMale = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        EmailLine = new javax.swing.JLabel();
        errorEmail = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        PasswordLine = new javax.swing.JLabel();
        errorPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ConfirmLine = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dispFnameLine = new javax.swing.JLabel();
        errorDispFname = new javax.swing.JLabel();
        dispFname = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dispLnameLine = new javax.swing.JLabel();
        errorDispLname = new javax.swing.JLabel();
        dispLname = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        dispPhoneLine = new javax.swing.JLabel();
        errorDispPhone = new javax.swing.JLabel();
        dispPhone = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        dispGenderLine = new javax.swing.JLabel();
        errorDispGender = new javax.swing.JLabel();
        dispGender = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        dispEmailLine = new javax.swing.JLabel();
        errorDispEmail = new javax.swing.JLabel();
        dispEmail = new javax.swing.JTextField();
        btnUpdtGeneral = new javax.swing.JButton();
        goToPassword = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        dispPwdLine1 = new javax.swing.JLabel();
        errorDispPwd1 = new javax.swing.JLabel();
        txtCurrentPwd = new javax.swing.JPasswordField();
        jPanel22 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        dispPwdLine2 = new javax.swing.JLabel();
        errorDispPwd2 = new javax.swing.JLabel();
        txtNewPwd = new javax.swing.JPasswordField();
        jPanel23 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        dispPwdLine3 = new javax.swing.JLabel();
        errorDispPwd3 = new javax.swing.JLabel();
        txtConfirmPwd = new javax.swing.JPasswordField();
        btnChangePwd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setOpaque(false);
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowAllStud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAllStud.setText("Show All");
        btnShowAllStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAllStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllStudActionPerformed(evt);
            }
        });
        jPanel29.add(btnShowAllStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 35));

        btnDelStud.setBackground(java.awt.Color.red);
        btnDelStud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDelStud.setForeground(new java.awt.Color(255, 255, 255));
        btnDelStud.setText("Delete");
        btnDelStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStudActionPerformed(evt);
            }
        });
        jPanel29.add(btnDelStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 35));

        btnGoToAddStud.setBackground(java.awt.SystemColor.textHighlight);
        btnGoToAddStud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToAddStud.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToAddStud.setText("Add");
        btnGoToAddStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToAddStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToAddStudActionPerformed(evt);
            }
        });
        jPanel29.add(btnGoToAddStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 35));

        btnUpdtRecord.setText("Update");
        btnUpdtRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdtRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdtRecordActionPerformed(evt);
            }
        });
        jPanel29.add(btnUpdtRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 35));

        btnViewStud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnViewStud.setText("View");
        btnViewStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudActionPerformed(evt);
            }
        });
        jPanel29.add(btnViewStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 35));

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 250));

        jPanel73.setBackground(new java.awt.Color(255, 255, 255));
        jPanel73.setOpaque(false);
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel74.setBackground(new java.awt.Color(255, 255, 255));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel104.setText("3");
        jPanel74.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 130, 20));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel105.setText("Manager Accounts");
        jPanel74.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 130, 20));

        jPanel73.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 180, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(java.awt.SystemColor.textHighlight);
        jLabel16.setText("Crud");
        jPanel73.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 3, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("4");
        jPanel73.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 3, 15, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel45.setForeground(java.awt.SystemColor.textHighlight);
        jLabel45.setText("Prac");
        jPanel73.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 3, -1, 20));

        jLabel8.setBackground(java.awt.SystemColor.textHighlight);
        jLabel8.setOpaque(true);
        jPanel73.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 35, 107, 1));

        jPanel1.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbl_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "First ", "Last ", "Phone", "Gender"
            }
        ));
        tbl_users.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbl_users.setColorBordeHead(new java.awt.Color(0, 112, 192));
        tbl_users.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_users.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_users.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_users.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_users.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_users.setFuenteHead(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        tbl_users.setGrosorBordeFilas(0);
        tbl_users.setGrosorBordeHead(0);
        tbl_users.setMultipleSeleccion(false);
        tbl_users.setRowHeight(25);
        tbl_users.setShowHorizontalLines(false);
        tbl_users.setShowVerticalLines(false);
        tbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_users);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("View User Info");

        jPanel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel45.setOpaque(false);
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.windowBorder);
        jLabel3.setText("First Name:");
        jPanel45.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        userFname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(userFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel52.setForeground(java.awt.SystemColor.windowBorder);
        jLabel52.setText("Last Name:");
        jPanel45.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        userLname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(userLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 190, 20));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel54.setForeground(java.awt.SystemColor.windowBorder);
        jLabel54.setText("Identification No:");
        jPanel45.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        userGender.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(userGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 140, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Basic Infomartion");
        jPanel45.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel55.setForeground(java.awt.SystemColor.windowBorder);
        jLabel55.setText("Gender:");
        jPanel45.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        userIdNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(userIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 20));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel56.setForeground(java.awt.SystemColor.windowBorder);
        jLabel56.setText("Status:");
        jPanel45.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        userStatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(userStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 110, 20));

        jPanel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel46.setOpaque(false);
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(java.awt.SystemColor.windowBorder);
        jLabel17.setText("Email Address:");
        jPanel46.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel46.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 20));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel40.setForeground(java.awt.SystemColor.windowBorder);
        jLabel40.setText("Phone number:");
        jPanel46.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, -1));

        userPhone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel46.add(userPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Contact Infomartion");
        jPanel46.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Create new account");

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        txtFname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtFname.setForeground(java.awt.Color.gray);
        txtFname.setText("first name");
        txtFname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnameFocusLost(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });
        jPanel7.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        FnameLine.setBackground(java.awt.Color.darkGray);
        FnameLine.setOpaque(true);
        jPanel7.add(FnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorFname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorFname.setForeground(java.awt.Color.red);
        jPanel7.add(errorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        txtLname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtLname.setForeground(java.awt.Color.gray);
        txtLname.setText("last name");
        txtLname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLnameFocusLost(evt);
            }
        });
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLnameKeyReleased(evt);
            }
        });
        jPanel8.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        LnameLine.setBackground(java.awt.Color.darkGray);
        LnameLine.setOpaque(true);
        jPanel8.add(LnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorLname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorLname.setForeground(java.awt.Color.red);
        jPanel8.add(errorLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/phone.png"))); // NOI18N
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPhone.setForeground(java.awt.Color.gray);
        txtPhone.setText("07xxxxxxxx");
        txtPhone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel10.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        PhoneLine.setBackground(java.awt.Color.darkGray);
        PhoneLine.setOpaque(true);
        jPanel10.add(PhoneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorPhone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorPhone.setForeground(java.awt.Color.red);
        jPanel10.add(errorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFemale.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnFemale.setText("Female");
        btnFemale.setOpaque(false);
        jPanel11.add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 6, -1, -1));

        btnMale.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnMale.setSelected(true);
        btnMale.setText("Male");
        btnMale.setOpaque(false);
        jPanel11.add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 6, -1, -1));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email.png"))); // NOI18N
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 30, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("someone@newmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel12.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 300, 27));

        EmailLine.setBackground(java.awt.Color.darkGray);
        EmailLine.setOpaque(true);
        jPanel12.add(EmailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 360, 1));

        errorEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorEmail.setForeground(java.awt.Color.red);
        jPanel12.add(errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 340, -1));

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        PasswordLine.setBackground(java.awt.Color.darkGray);
        PasswordLine.setOpaque(true);
        jPanel13.add(PasswordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorPassword.setForeground(java.awt.Color.red);
        jPanel13.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPassword.setForeground(java.awt.Color.gray);
        txtPassword.setText("yourpassword");
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel13.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        ConfirmLine.setBackground(java.awt.Color.darkGray);
        ConfirmLine.setOpaque(true);
        jPanel14.add(ConfirmLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        txtConfirm.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtConfirm.setForeground(java.awt.Color.gray);
        txtConfirm.setText("yourpassword");
        txtConfirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmFocusLost(evt);
            }
        });
        jPanel14.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        btnSignUp.setBackground(java.awt.SystemColor.textHighlight);
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSignUp.setForeground(java.awt.Color.white);
        btnSignUp.setText("Sign Up");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Update this account");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispFnameLine.setBackground(java.awt.Color.darkGray);
        dispFnameLine.setOpaque(true);
        jPanel9.add(dispFnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorDispFname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispFname.setForeground(java.awt.Color.red);
        jPanel9.add(errorDispFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        dispFname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dispFname.setBorder(null);
        jPanel9.add(dispFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispLnameLine.setBackground(java.awt.Color.darkGray);
        dispLnameLine.setOpaque(true);
        jPanel16.add(dispLnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorDispLname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispLname.setForeground(java.awt.Color.red);
        jPanel16.add(errorDispLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        dispLname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dispLname.setBorder(null);
        jPanel16.add(dispLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/phone.png"))); // NOI18N
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispPhoneLine.setBackground(java.awt.Color.darkGray);
        dispPhoneLine.setOpaque(true);
        jPanel17.add(dispPhoneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorDispPhone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispPhone.setForeground(java.awt.Color.red);
        jPanel17.add(errorDispPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        dispPhone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dispPhone.setBorder(null);
        jPanel17.add(dispPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel18.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispGenderLine.setBackground(java.awt.Color.darkGray);
        dispGenderLine.setOpaque(true);
        jPanel18.add(dispGenderLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorDispGender.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispGender.setForeground(java.awt.Color.red);
        jPanel18.add(errorDispGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        dispGender.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dispGender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel18.add(dispGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email.png"))); // NOI18N
        jPanel19.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispEmailLine.setBackground(java.awt.Color.darkGray);
        dispEmailLine.setOpaque(true);
        jPanel19.add(dispEmailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 365, 1));

        errorDispEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispEmail.setForeground(java.awt.Color.red);
        jPanel19.add(errorDispEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 350, -1));

        dispEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dispEmail.setBorder(null);
        jPanel19.add(dispEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 310, 27));

        btnUpdtGeneral.setBackground(java.awt.SystemColor.textHighlight);
        btnUpdtGeneral.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnUpdtGeneral.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdtGeneral.setText("Update");
        btnUpdtGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdtGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdtGeneralActionPerformed(evt);
            }
        });

        goToPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        goToPassword.setForeground(java.awt.SystemColor.textHighlight);
        goToPassword.setText("Change Password");
        goToPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnUpdtGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(goToPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goToPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdtGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Update password of this account");

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel21.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispPwdLine1.setBackground(java.awt.Color.darkGray);
        dispPwdLine1.setOpaque(true);
        jPanel21.add(dispPwdLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 265, 1));

        errorDispPwd1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispPwd1.setForeground(java.awt.Color.red);
        jPanel21.add(errorDispPwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 250, 20));

        txtCurrentPwd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCurrentPwd.setForeground(java.awt.Color.gray);
        txtCurrentPwd.setText("yourpassword");
        txtCurrentPwd.setBorder(null);
        txtCurrentPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCurrentPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCurrentPwdFocusLost(evt);
            }
        });
        jPanel21.add(txtCurrentPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 210, 27));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel22.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispPwdLine2.setBackground(java.awt.Color.darkGray);
        dispPwdLine2.setOpaque(true);
        jPanel22.add(dispPwdLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 265, 1));

        errorDispPwd2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispPwd2.setForeground(java.awt.Color.red);
        jPanel22.add(errorDispPwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 250, 20));

        txtNewPwd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNewPwd.setForeground(java.awt.Color.gray);
        txtNewPwd.setText("yourpassword");
        txtNewPwd.setBorder(null);
        txtNewPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPwdFocusLost(evt);
            }
        });
        txtNewPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPwdKeyReleased(evt);
            }
        });
        jPanel22.add(txtNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 210, 27));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel23.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        dispPwdLine3.setBackground(java.awt.Color.darkGray);
        dispPwdLine3.setOpaque(true);
        jPanel23.add(dispPwdLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 265, 1));

        errorDispPwd3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorDispPwd3.setForeground(java.awt.Color.red);
        jPanel23.add(errorDispPwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 250, 20));

        txtConfirmPwd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtConfirmPwd.setForeground(java.awt.Color.gray);
        txtConfirmPwd.setText("yourpassword");
        txtConfirmPwd.setBorder(null);
        txtConfirmPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPwdFocusLost(evt);
            }
        });
        jPanel23.add(txtConfirmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 210, 27));

        btnChangePwd.setBackground(java.awt.SystemColor.textHighlight);
        btnChangePwd.setForeground(java.awt.Color.white);
        btnChangePwd.setText("Change");
        btnChangePwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel20);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -32, 566, 390));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 570, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllStudActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        
        btnViewStud.setVisible(false);
        btnUpdtRecord.setVisible(false);
        btnDelStud.setVisible(false);
    }//GEN-LAST:event_btnShowAllStudActionPerformed

    private void btnViewStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        
        btnViewStud.setVisible(true);
        btnUpdtRecord.setVisible(true);
        btnDelStud.setVisible(true);
    }//GEN-LAST:event_btnViewStudActionPerformed

    private void btnDelStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStudActionPerformed
        // Operation for deleting student account
        defaulttbl_3_delete = (DefaultTableModel)tbl_users.getModel();
        int selectIndex = tbl_users.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_3_delete.getValueAt(selectIndex, 0).toString());

        // confirmation message
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete Account of this User", "Warnimg", JOptionPane.YES_NO_OPTION);

        if(dialogResult == JOptionPane.YES_OPTION){           
            try {
                Connection conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("delete from tbl_users where id=?");
                sqlQueryCheck.setInt(1, id);
                sqlQueryCheck.executeUpdate();

                JOptionPane.showMessageDialog(null, "Account has been Deleted Successfully");

                users_table();
                
                // refreshing the current page
                new Crud().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDelStudActionPerformed

    private void btnGoToAddStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToAddStudActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        
        btnViewStud.setVisible(false);
        btnUpdtRecord.setVisible(false);
        btnDelStud.setVisible(false);
    }//GEN-LAST:event_btnGoToAddStudActionPerformed

    private void btnUpdtRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdtRecordActionPerformed
        // Operation for updating specific record
        jTabbedPane1.setSelectedIndex(3);
        
        btnViewStud.setVisible(true);
        btnUpdtRecord.setVisible(true);
        btnDelStud.setVisible(true);

        defaulttbl_4_update = (DefaultTableModel)tbl_users.getModel();
        int selectIndex = tbl_users.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_4_update.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_users where id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String fetchFname  = res.getString("firstname");
                String fetchLname  = res.getString("lastname");
                String fetchPhone  = "0"+res.getString("phone");
                String fetchGender = res.getString("gender");
                String fetchEmail  = res.getString("email");
                
                // display users details
                dispFname.setText(fetchFname);
                dispLname.setText(fetchLname);
                dispPhone.setText(fetchPhone);
                dispGender.setText(fetchGender);
                dispEmail.setText(fetchEmail);
            }
        } catch (Exception ex) {
            Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdtRecordActionPerformed

    /**
     * Form validation
     */
    private void txtFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusGained
        if(txtFname.getText().trim().toLowerCase().equals("first name")){
            txtFname.setText("");
            txtFname.setForeground(Color.black);
            FnameLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtFnameFocusGained

    private void txtFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusLost
        if(txtFname.getText().trim().equals("") || txtFname.getText().trim().equals("first name")){
            txtFname.setText("first name");
            txtFname.setForeground(Color.gray);
            FnameLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtFnameFocusLost

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
        // validate the input of this field
        String PATTERN = "^[a-z A-Z]{0,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtFname.getText());

        if(!match.matches()) {
            errorFname.setText("Invalid first name!");
        } else {
            errorFname.setText(null);
        }
    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusGained
        if(txtLname.getText().trim().toLowerCase().equals("last name")){
            txtLname.setText("");
            txtLname.setForeground(Color.black);
            LnameLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtLnameFocusGained

    private void txtLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusLost
        if(txtLname.getText().trim().equals("") || txtLname.getText().trim().equals("last name")){
            txtLname.setText("last name");
            txtLname.setForeground(Color.gray);
            LnameLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtLnameFocusLost

    private void txtLnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyReleased
        // validate the input of this field
        String PATTERN = "^[a-z A-Z]{0,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtLname.getText());

        if(!match.matches()) {
            errorLname.setText("Invalid last name!");
        } else {
            errorLname.setText(null);
        }
    }//GEN-LAST:event_txtLnameKeyReleased

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        if(txtPhone.getText().trim().toLowerCase().equals("07xxxxxxxx")){
            txtPhone.setText("");
            txtPhone.setForeground(Color.black);
            PhoneLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        if(txtPhone.getText().trim().equals("") || txtPhone.getText().trim().equals("07xxxxxxxx")){
            txtPhone.setText("07xxxxxxxx");
            txtPhone.setForeground(Color.gray);
            PhoneLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        // validate the input of this field
        String PATTERN = "^[0-9 0-9]{0,10}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtPhone.getText());

        if(!match.matches()) {
            errorPhone.setText("Invalid phonenumber!");
        } else {
            errorPhone.setText(null);
        }
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().trim().toLowerCase().equals("someone@newmail.com")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
            EmailLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals("someone@newmail.com")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            EmailLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // validating email field to ensure (@) and (.) symbol are not ommitted
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{1,10}[.][a-zA-Z0-9]{2,5}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtEmail.getText());

        if(!match.matches()) {
            errorEmail.setText("Invalid email address!");
        } else {
            errorEmail.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(txtPassword.getText().trim().toLowerCase().equals("yourpassword")){
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
            PasswordLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(txtPassword.getText().trim().equals("") || txtPassword.getText().trim().equals("yourpassword")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            PasswordLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        String PATTERN = "^[a-zA-Z0-9_!@#$%^&*-?]{10,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtPassword.getText());

        if(!match.matches()) {
            errorPassword.setText("Invalid Password/Its too short!");
        } else {
            errorPassword.setText(null);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusGained
        if(txtConfirm.getText().trim().toLowerCase().equals("yourpassword")){
            txtConfirm.setText("");
            txtConfirm.setForeground(Color.black);
            ConfirmLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtConfirmFocusGained

    private void txtConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusLost
        if(txtConfirm.getText().trim().equals("") || txtConfirm.getText().trim().equals("yourpassword")){
            txtConfirm.setText("yourpassword");
            txtConfirm.setForeground(Color.gray);
            ConfirmLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtConfirmFocusLost

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // operation of createing a new account
        String status   = "Offline";
        String first    = txtFname.getText();
        String last     = txtLname.getText();
        String phone    = txtPhone.getText();
        String gender   = "Male";
        if(btnFemale.isSelected()) { gender  = "Female"; }
        String email    = txtEmail.getText();
        String password = txtPassword.getText();
        String confirm  = txtConfirm.getText();

        // checking if any field is empty before submitting the form
        if(first.trim().equals("") || first.trim().equals("first name")){
            errorFname.setText("first name is empty!");
        }
        else if(last.trim().equals("") || last.trim().equals("last name")){
            errorLname.setText("last name is empty!");
        }
        else if(phone.trim().equals("") || phone.trim().equals("07xxxxxxxx")){
            errorPhone.setText("phonenumber is empty!");
        }
        else if(email.trim().equals("") || email.trim().equals("someone@newmail.com")){
            errorEmail.setText("Email is empty!");
        }
        else if(password.trim().equals("") || password.trim().equals("yourpassword")){
            errorPassword.setText("password is empty!");
        }
        else if (password.equals(confirm)) {
            try {
                // conform if cridentials used already exist in the Database
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_users where phone=? or email=? ");
                sqlQueryCheck.setString(1, phone);
                sqlQueryCheck.setString(2, email);
                res = sqlQueryCheck.executeQuery();

                if(res.isBeforeFirst()) {
                    // if the credential already exist display error message
                    JOptionPane.showMessageDialog(this, "These Cridentials have been used by another User", "Please use new Cridentials", JOptionPane.ERROR_MESSAGE);

                    // clearing neccessary fields to allow the admin to re-enter new Cridentials
                    clear_form();
                }
                else {
                    sqlQueryInsert = conn.prepareStatement("insert into tbl_users (status,firstname,lastname,phone,gender,email,password) values (?,?,?,?,?,?,?) ");
                    sqlQueryInsert.setString(1, status);
                    sqlQueryInsert.setString(2, first);
                    sqlQueryInsert.setString(3, last);
                    sqlQueryInsert.setString(4, phone);
                    sqlQueryInsert.setString(5, gender);
                    sqlQueryInsert.setString(6, email);
                    sqlQueryInsert.setString(7, password);

                    //if the record is inserted successfully the state of executeUpdate() will be 1
                    if (sqlQueryInsert.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "You account has been created successfully.");

                        // clearing the form after successfully adding the new record in the database
                        clear_form();

                        // refresh the page
                        new Crud().setVisible(true);
                        this.dispose();

                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Confirm Password doesn't match with Password!", "Please Try again", JOptionPane.ERROR_MESSAGE);
            txtConfirm.setText("");
            if(txtConfirm.getText().trim().equals("")){
                txtConfirm.setText("yourpassword");
                txtConfirm.setForeground(Color.gray);
                ConfirmLine.setBackground(Color.black);
            }

            return;
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // operation for reseting account form
        clear_form();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tbl_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usersMouseClicked
        // Operation that happens after clicking any row
        btnViewStud.setVisible(true);
        btnUpdtRecord.setVisible(true);
        btnDelStud.setVisible(true);
        
        defaulttbl_2_view = (DefaultTableModel)tbl_users.getModel();
        int selectIndex = tbl_users.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_2_view.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_users where id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String fetchId     = res.getString("id");
                String fetchStatus = res.getString("status");
                String fetchFname  = res.getString("firstname");
                String fetchLname  = res.getString("lastname");
                String fetchPhone  = "0"+res.getString("phone");
                String fetchGender = res.getString("gender");
                String fetchEmail  = res.getString("email");
                
                // display users details
                userIdNo.setText(fetchId);
                userStatus.setText(fetchStatus);
                userFname.setText(fetchFname);
                userLname.setText(fetchLname);
                userPhone.setText(fetchPhone);
                userGender.setText(fetchGender);
                userEmail.setText(fetchEmail);
            }
        } catch (Exception ex) {
            Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_usersMouseClicked

    private void btnUpdtGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdtGeneralActionPerformed
        // Operation of updating general info
        String first    = dispFname.getText();
        String last     = dispLname.getText();
        String phone    = dispPhone.getText();
        String gender   = dispGender.getText();
        String email    = dispEmail.getText();
        
        defaulttbl_5_update = (DefaultTableModel)tbl_users.getModel();
        int selectIndex = tbl_users.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_5_update.getValueAt(selectIndex, 0).toString());
        
        try {
            conn = DBConnection.setConnection();
            sqlQueryUpdate = conn.prepareStatement("update tbl_users set firstname=?, lastname=?, phone=?, gender=?, email=? where id=? ");
            sqlQueryUpdate.setString(1, first);
            sqlQueryUpdate.setString(2, last);
            sqlQueryUpdate.setString(3, phone);
            sqlQueryUpdate.setString(4, gender);
            sqlQueryUpdate.setString(5, email);
            sqlQueryUpdate.setInt(6, id);
            
            if (sqlQueryUpdate.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "Account was updated successfully.");
                users_table();
                
                // clear the form
                dispFname.setText("");
                dispLname.setText("");
                dispPhone.setText("");
                dispGender.setText("");
                dispEmail.setText("");
                
                //refresh the page
                new Crud().setVisible(true);
                this.dispose();
                
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdtGeneralActionPerformed

    /**
     * Form validation
     */
    private void txtCurrentPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPwdFocusGained
        if(txtCurrentPwd.getText().trim().toLowerCase().equals("yourpassword")){
            txtCurrentPwd.setText("");
            txtCurrentPwd.setForeground(Color.black);
            dispPwdLine1.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtCurrentPwdFocusGained

    private void txtCurrentPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPwdFocusLost
        if(txtCurrentPwd.getText().trim().equals("") || txtCurrentPwd.getText().trim().equals("yourpassword")){
            txtCurrentPwd.setText("yourpassword");
            txtCurrentPwd.setForeground(Color.gray);
            dispPwdLine1.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtCurrentPwdFocusLost

    private void txtNewPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPwdFocusGained
        if(txtNewPwd.getText().trim().toLowerCase().equals("yourpassword")){
            txtNewPwd.setText("");
            txtNewPwd.setForeground(Color.black);
            dispPwdLine2.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtNewPwdFocusGained

    private void txtNewPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPwdFocusLost
        if(txtNewPwd.getText().trim().equals("") || txtNewPwd.getText().trim().equals("yourpassword")){
            txtNewPwd.setText("yourpassword");
            txtNewPwd.setForeground(Color.gray);
            dispPwdLine2.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtNewPwdFocusLost

    private void txtNewPwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPwdKeyReleased
        String PATTERN = "^[a-zA-Z0-9_!@#$%^&*-?]{10,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtNewPwd.getText());

        if(!match.matches()) {
            errorDispPwd2.setText("Invalid Password/Its too short!");
        } else {
            errorDispPwd2.setText(null);
        }
    }//GEN-LAST:event_txtNewPwdKeyReleased

    private void txtConfirmPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPwdFocusGained
        if(txtConfirmPwd.getText().trim().toLowerCase().equals("yourpassword")){
            txtConfirmPwd.setText("");
            txtConfirmPwd.setForeground(Color.black);
            dispPwdLine3.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtConfirmPwdFocusGained

    private void txtConfirmPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPwdFocusLost
        if(txtConfirmPwd.getText().trim().equals("") || txtConfirmPwd.getText().trim().equals("yourpassword")){
            txtConfirmPwd.setText("yourpassword");
            txtConfirmPwd.setForeground(Color.gray);
            dispPwdLine3.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtConfirmPwdFocusLost

    private void btnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePwdActionPerformed
        // operation for changing the password
        String current  = String.valueOf(txtCurrentPwd.getPassword());
        String newpwd   = String.valueOf(txtNewPwd.getPassword());
        String confpwd  = String.valueOf(txtConfirmPwd.getPassword());
        
        defaulttbl_6_update = (DefaultTableModel)tbl_users.getModel();
        int selectIndex = tbl_users.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_6_update.getValueAt(selectIndex, 0).toString());

        // checking if any field is empty before submitting the form
        if(current.trim().equals("") || current.trim().equals("yourpassword")){
            errorDispPwd1.setText("Password is missing!");
        }
        else if(newpwd.trim().equals("") || newpwd.trim().equals("yourpassword")){
            errorDispPwd2.setText("Password is missing!");
        }
        else if(confpwd.trim().equals("") || confpwd.trim().equals("yourpassword")){
            errorDispPwd3.setText("Password is missing!");
        }
        else {
            try {
                // checking if user credential already exist
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_users where id=? ");
                sqlQueryCheck.setInt(1, id);
                res = sqlQueryCheck.executeQuery();

                // if the id is in the database then Proceed
                if(res.next()){
                    // retrieve the password in the db
                    String retrievePass = res.getString("password");

                    // checking if password provided matches with the one in the database
                    if (retrievePass.equals(current)) {
                        // checking if new password is the same as confirm password
                        if (newpwd.equals(confpwd)) {
                            // update the password which is in the database
                            sqlQueryUpdate = conn.prepareStatement("update tbl_users SET password=? WHERE id=? ");
                            sqlQueryUpdate.setString(1, newpwd);
                            sqlQueryUpdate.setInt(2, id);

                            if (sqlQueryUpdate.executeUpdate() != 0) {
                                // Show success mesage
                                JOptionPane.showMessageDialog(this, "Password changed successfully.");
                                JOptionPane.showMessageDialog(this, "Next time use your new password to login");

                                txtCurrentPwd.setText("yourpassword");
                                txtNewPwd.setText("yourpassword");
                                txtConfirmPwd.setText("yourpassword");

                                // refresh the page
                                new Crud().setVisible(true);
                                this.dispose();

                                return;
                            }
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Confirm Password doesn't match with New Password!", "Please Try again", JOptionPane.ERROR_MESSAGE);
                            txtConfirmPwd.setText("");

                            txtConfirmPwd.requestFocus();
                        }
                    }
                    else {
                        errorDispPwd1.setText("Invalid Password!");
                        txtCurrentPwd.setText("");

                        txtCurrentPwd.requestFocus();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnChangePwdActionPerformed

    private void goToPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPasswordMouseClicked
        jTabbedPane1.setSelectedIndex(4);
        
        btnViewStud.setVisible(true);
        btnUpdtRecord.setVisible(true);
        btnDelStud.setVisible(true);
    }//GEN-LAST:event_goToPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmLine;
    private javax.swing.JLabel EmailLine;
    private javax.swing.JLabel FnameLine;
    private javax.swing.JLabel LnameLine;
    private javax.swing.JLabel PasswordLine;
    private javax.swing.JLabel PhoneLine;
    private javax.swing.JButton btnChangePwd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelStud;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JButton btnGoToAddStud;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JButton btnShowAllStud;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnUpdtGeneral;
    private javax.swing.JButton btnUpdtRecord;
    private javax.swing.JButton btnViewStud;
    private javax.swing.JTextField dispEmail;
    private javax.swing.JLabel dispEmailLine;
    private javax.swing.JTextField dispFname;
    private javax.swing.JLabel dispFnameLine;
    private javax.swing.JTextField dispGender;
    private javax.swing.JLabel dispGenderLine;
    private javax.swing.JTextField dispLname;
    private javax.swing.JLabel dispLnameLine;
    private javax.swing.JTextField dispPhone;
    private javax.swing.JLabel dispPhoneLine;
    private javax.swing.JLabel dispPwdLine1;
    private javax.swing.JLabel dispPwdLine2;
    private javax.swing.JLabel dispPwdLine3;
    private javax.swing.JLabel errorDispEmail;
    private javax.swing.JLabel errorDispFname;
    private javax.swing.JLabel errorDispGender;
    private javax.swing.JLabel errorDispLname;
    private javax.swing.JLabel errorDispPhone;
    private javax.swing.JLabel errorDispPwd1;
    private javax.swing.JLabel errorDispPwd2;
    private javax.swing.JLabel errorDispPwd3;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorFname;
    private javax.swing.JLabel errorLname;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel errorPhone;
    private javax.swing.JLabel goToPassword;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private rojeru_san.complementos.RSTableMetro tbl_users;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtConfirmPwd;
    private javax.swing.JPasswordField txtCurrentPwd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtNewPwd;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userFname;
    private javax.swing.JLabel userGender;
    private javax.swing.JLabel userIdNo;
    private javax.swing.JLabel userLname;
    private javax.swing.JLabel userPhone;
    private javax.swing.JLabel userStatus;
    // End of variables declaration//GEN-END:variables
}
